# Generated by Django 3.1.4 on 2020-12-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_applications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
    ]
