# Generated by Django 3.1.4 on 2021-02-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_application_displayusernames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reviewer',
            field=models.CharField(choices=[('Naresh Kumar', 'Naresh Kumar'), ('Sanjay', 'Sanjay')], max_length=200, null=True),
        ),
    ]
