# Generated by Django 3.1.4 on 2021-03-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210201_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='discord_handle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='github_handle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tasksrepo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
