# Generated by Django 3.1.4 on 2020-12-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201210_0739'),
        ('pages', '0005_auto_20201210_1216'),
    ]

    operations = [
    ]
