# Generated by Django 3.1.4 on 2021-03-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210301_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reviewer',
            field=models.CharField(choices=[('Sanjay', 'Sanjay'), ('Naresh Kumar', 'Naresh Kumar')], max_length=200, null=True),
        ),
    ]
