# Generated by Django 3.1.4 on 2020-12-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_merge_20201210_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='feedback',
        ),
    ]
