# Generated by Django 3.1.4 on 2021-03-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210302_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='github_handle',
            new_name='github_username',
        ),
    ]
