# Generated by Django 3.1.4 on 2020-12-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_application_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reviewer',
            field=models.CharField(choices=[], max_length=100, null=True),
        ),
    ]
