# Generated by Django 3.1.4 on 2021-03-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210302_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reviewer',
            field=models.CharField(choices=[('Sanjai Siddharthan', 'Sanjai Siddharthan'), ('TEJENDRA SARADHI', 'TEJENDRA SARADHI'), ('Naresh Kumar', 'Naresh Kumar'), ('Sanjay', 'Sanjay')], max_length=200, null=True),
        ),
    ]
