# Generated by Django 3.1.4 on 2021-01-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20201223_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reviewer',
            field=models.CharField(choices=[], max_length=200, null=True),
        ),
    ]
