# Generated by Django 3.1.4 on 2021-01-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Streak',
        ),
    ]
