# Generated by Django 3.1.4 on 2021-01-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
        migrations.DeleteModel(
            name='Membs',
        ),
    ]
