# Generated by Django 3.1.4 on 2021-01-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_achievement_meeting_statusupdate_streakcount_submission_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='organiser',
            field=models.CharField(choices=[('Naresh Kumar', 'Naresh Kumar')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='evaluator',
            field=models.CharField(choices=[('Naresh Kumar', 'Naresh Kumar')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(choices=[('Naresh Kumar', 'Naresh Kumar')], max_length=200, null=True),
        ),
    ]
