# Generated by Django 3.1.4 on 2021-01-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_auto_20210111_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.DeleteModel(
            name='StatusUpdate',
        ),
        migrations.RemoveField(
            model_name='streakcount',
            name='username',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Streakcount',
        ),
    ]
