# Generated by Django 3.1.4 on 2020-12-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
