# Generated by Django 3.1.4 on 2021-01-21 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_auto_20210121_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streakcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak', models.IntegerField(null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminapp.member')),
            ],
        ),
    ]
