# Generated by Django 3.1.4 on 2020-12-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_auto_20201208_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(choices=[('Sanjay', 'Sanjay'), ('Pranavan', 'Pranavan')], max_length=200, null=True),
        ),
    ]
