# Generated by Django 3.1.4 on 2021-01-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('goal', models.CharField(max_length=500, null=True)),
                ('author', models.CharField(choices=[], max_length=200, null=True)),
                ('content', models.TextField(max_length=2000, null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('starting_time', models.DateTimeField(null=True)),
                ('max_score', models.FloatField(null=True)),
                ('group', models.CharField(choices=[], max_length=200, null=True)),
                ('resource_file', models.FileField(null=True, upload_to='')),
                ('submission_link', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
