# Generated by Django 3.1.4 on 2021-01-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(null=True)),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('score', models.FloatField(max_length=50, null=True)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('submission_file', models.FileField(null=True, upload_to='')),
                ('submission_text', models.CharField(max_length=500, null=True)),
                ('evaluator', models.CharField(choices=[], max_length=200, null=True)),
                ('feedback', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
