# Generated by Django 3.1.4 on 2021-01-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500, null=True)),
                ('venue', models.DateTimeField(max_length=200, null=True)),
                ('organiser', models.CharField(choices=[], max_length=200, null=True)),
                ('group', models.CharField(choices=[], max_length=200, null=True)),
                ('meeting_link', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
            ],
        ),
    ]
