# Generated by Django 3.1.4 on 2021-01-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_meeting_statusupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusupdate',
            name='reportdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='group',
            field=models.CharField(choices=[('administrator', 'administrator'), ('member', 'member')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.CharField(choices=[('administrator', 'administrator'), ('member', 'member')], max_length=200, null=True),
        ),
    ]
