# Generated by Django 3.1.4 on 2020-12-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_auto_20201209_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(choices=[('Sanjay', 'Sanjay'), ('Pranavan', 'Pranavan')], max_length=200, null=True),
        ),
    ]
