# Generated by Django 3.1.4 on 2020-12-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_auto_20201209_0901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievements',
            new_name='Achievement',
        ),
    ]
