# Generated by Django 3.1.4 on 2020-12-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_auto_20201209_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(max_length=10, null=True)),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('score', models.FloatField(max_length=50, null=True)),
                ('submitted_on', models.DateTimeField(null=True)),
                ('submission_file', models.FileField(null=True, upload_to='')),
                ('submission_text', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
