# Generated by Django 3.1.4 on 2020-12-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='evaluator',
            field=models.CharField(choices=[('Sanjay', 'Sanjay'), ('Pranavan', 'Pranavan')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
    ]
