# Generated by Django 3.1.4 on 2021-03-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_auto_20210301_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='organiser',
            field=models.CharField(choices=[('Sanjay', 'Sanjay'), ('Tejendra Saradhi', 'Tejendra Saradhi'), ('Naresh Kumar', 'Naresh Kumar')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='streak',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='evaluator',
            field=models.CharField(choices=[('Sanjay', 'Sanjay'), ('Tejendra Saradhi', 'Tejendra Saradhi'), ('Naresh Kumar', 'Naresh Kumar')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(choices=[('Sanjay', 'Sanjay'), ('Tejendra Saradhi', 'Tejendra Saradhi'), ('Naresh Kumar', 'Naresh Kumar')], max_length=200, null=True),
        ),
    ]
