# Generated by Django 3.1.4 on 2020-12-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_auto_20201219_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
