# Generated by Django 3.1.4 on 2020-12-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_submission_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='evaluator',
            field=models.CharField(choices=[], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(choices=[], max_length=200, null=True),
        ),
    ]
