# Generated by Django 3.1.4 on 2021-03-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_auto_20210302_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='organiser',
            field=models.CharField(choices=[('Tejendra Saradhi', 'Tejendra Saradhi'), ('Sanjay', 'Sanjay'), ('Naresh Kumar', 'Naresh Kumar')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='evaluator',
            field=models.CharField(choices=[('Tejendra Saradhi', 'Tejendra Saradhi'), ('Sanjay', 'Sanjay'), ('Naresh Kumar', 'Naresh Kumar')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(choices=[('Tejendra Saradhi', 'Tejendra Saradhi'), ('Sanjay', 'Sanjay'), ('Naresh Kumar', 'Naresh Kumar')], max_length=200, null=True),
        ),
    ]
