# Generated by Django 3.1.4 on 2020-12-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_auto_20201219_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='evaluator',
            field=models.CharField(choices=[('Sanjay', 'Sanjay'), ('Pranavan', 'Pranavan')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(choices=[('Sanjay', 'Sanjay'), ('Pranavan', 'Pranavan')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.CharField(choices=[('administrator', 'administrator'), ('member', 'member'), ('Cyber Security', 'Cyber Security'), ('Mentors', 'Mentors')], max_length=200, null=True),
        ),
    ]
