# Generated by Django 3.1.4 on 2020-12-20 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_auto_20201219_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
