# Generated by Django 3.1.4 on 2020-12-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_auto_20201220_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='evaluator',
            field=models.CharField(choices=[('Sanjay', 'Sanjay'), ('Naresh Kumar', 'Naresh Kumar')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(choices=[('Sanjay', 'Sanjay'), ('Naresh Kumar', 'Naresh Kumar')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.CharField(choices=[('member', 'member'), ('administrator', 'administrator'), ('Cyber Security', 'Cyber Security'), ('mentors', 'mentors'), ('Machine Learning', 'Machine Learning'), ('Open Source', 'Open Source'), ('Competitive Programming', 'Competitive Programming')], max_length=200, null=True),
        ),
    ]
