# Generated by Django 3.1.4 on 2020-12-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_auto_20201228_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Pics/'),
        ),
    ]
