# Generated by Django 3.1.4 on 2020-12-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='StatusUpdates',
        ),
    ]
