# Generated by Django 3.1.4 on 2020-12-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0026_auto_20201229_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupdates',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='statusupdates',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
