# Generated by Django 3.1.4 on 2020-12-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0028_auto_20201229_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusUpdates',
            new_name='StatusUpdate',
        ),
    ]
