# Generated by Django 3.1.4 on 2021-01-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0029_auto_20201229_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500, null=True)),
                ('venue', models.DateTimeField(max_length=200, null=True)),
                ('organiser', models.CharField(choices=[('Sanjay', 'Sanjay'), ('Naresh Kumar', 'Naresh Kumar')], max_length=200, null=True)),
                ('group', models.CharField(choices=[('member', 'member'), ('administrator', 'administrator'), ('Cyber Security', 'Cyber Security'), ('mentors', 'mentors'), ('Machine Learning', 'Machine Learning'), ('Open Source', 'Open Source'), ('Competitive Programming', 'Competitive Programming')], max_length=200, null=True)),
                ('meeting_link', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], max_length=200, null=True)),
            ],
        ),
    ]
