# Generated by Django 3.1.4 on 2021-01-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0030_meetings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meetings',
            new_name='Meeting',
        ),
    ]
